[pytest]
asyncio_mode = auto
testpaths = tests
markers =
    requires_postgres: Test requires a running PostgreSQL instance (use @pytest.mark.skip for CI)
filterwarnings =
    ignore::DeprecationWarning:datetime:
    ignore::sqlalchemy.exc.MovedIn20Warning
