#!/usr/bin/env python3
"""
Secret Rotation Script
Rotates environment secrets and generates secure random values.
Usage: python scripts/rotate_secrets.py [--dry-run] [--output .env.new]
"""
import secrets
import string
import argparse
import os
import re
from datetime import datetime


def generate_secret(length: int = 32) -> str:
    """Generate a cryptographically secure random secret."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*()_+-="
    return "".join(secrets.choice(alphabet) for _ in range(length))


def generate_uuid() -> str:
    """Generate a UUID v4."""
    import uuid
    return str(uuid.uuid4())


SECRETS_MAP = {
    "SECRET_KEY": lambda: generate_secret(64),
    "DATABASE_URL": None,  # Don't auto-rotate — requires manual update
    "OPENAI_API_KEY": None,  # Don't auto-rotate — requires manual input
    "ANTHROPIC_API_KEY": None,  # Don't auto-rotate
    "REDIS_URL": None,  # Don't auto-rotate
    "RESEND_API_KEY": None,  # Don't auto-rotate
    "SENDGRID_API_KEY": None,  # Don't auto-rotate
    "STRIPE_API_KEY": None,  # Don't auto-rotate
    "STRIPE_WEBHOOK_SECRET": lambda: generate_secret(32),
    "JWT_SECRET": lambda: generate_secret(64),
    "ENCRYPTION_KEY": lambda: generate_secret(32),
}


def rotate_secrets(env_file: str, dry_run: bool = False, output_file: str = None):
    """
    Rotate secrets in the .env file.

    Args:
        env_file: Path to the current .env file.
        dry_run: If True, only print what would change without modifying.
        output_file: If set, write new secrets to this file instead of overwriting.
    """
    if not os.path.exists(env_file):
        print(f"❌ File not found: {env_file}")
        print(f"   Create {env_file} with your current secrets first.")
        return

    with open(env_file, "r") as f:
        lines = f.readlines()

    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    changes = []
    new_lines = []

    for line in lines:
        line = line.rstrip("\n")

        # Skip comments and empty lines
        if not line or line.startswith("#"):
            new_lines.append(line)
            continue

        # Parse KEY=VALUE
        match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)", line)
        if not match:
            new_lines.append(line)
            continue

        key, _ = match.groups()

        if key in SECRETS_MAP and SECRETS_MAP[key] is not None:
            new_value = SECRETS_MAP[key]()
            new_lines.append(f"{key}={new_value}")
            changes.append(key)
            if dry_run:
                print(f"  🔄 {key}: would rotate")
        else:
            new_lines.append(line)

    if dry_run:
        print(f"\n📋 Dry run complete. {len(changes)} secrets would be rotated:")
        for key in changes:
            print(f"   - {key}")
        print("\nRun without --dry-run to apply changes.")
        return

    # Write output
    output_path = output_file or env_file
    with open(output_path, "w") as f:
        f.write("# Auto-generated by rotate_secrets.py\n")
        f.write(f"# Last rotated: {timestamp}\n")
        for line in new_lines:
            f.write(line + "\n")

    if output_file:
        print(f"✅ New secrets written to: {output_file}")
    else:
        print(f"✅ Secrets rotated in place: {env_file}")

    print(f"📝 Rotated {len(changes)} secrets:")
    for key in changes:
        print(f"   ✅ {key}")

    print("\n⚠️  IMPORTANT:")
    print("   - Update any services that use these secrets")
    print("   - Restart all containers after applying changes")
    print("   - Securely delete any old secret values")


def generate_env_template():
    """Generate a .env.example template with placeholder values."""
    template = """# AutoBiz Engine — Environment Variables Template
# Copy to .env and fill in actual values
# Last generated: {timestamp}

# ─── Application ──────────────────────────────────────────
APP_NAME=AutoBiz Engine
DEBUG=false
SECRET_KEY={secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# ─── CORS ─────────────────────────────────────────────────
CORS_ORIGINS=http://localhost:3000,http://localhost:8000

# ─── Database ─────────────────────────────────────────────
DATABASE_URL=postgresql+psycopg2://user:password@localhost/autobiz_engine
DATABASE_POOL_SIZE=10
DATABASE_POOL_TIMEOUT=30
DATABASE_ECHO=false

# ─── Redis ────────────────────────────────────────────────
REDIS_URL=redis://localhost:6379

# ─── Celery ───────────────────────────────────────────────
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0
CELERY_TASK_TRACK_STARTED=true
CELERY_WORKER_PREFETCH_MULTIPLIER=1

# ─── AI / LLM ─────────────────────────────────────────────
OPENAI_API_KEY=sk-your-openai-key-here
OPENAI_MODEL=gpt-4-turbo
ANTHROPIC_API_KEY=sk-your-anthropic-key-here

# ─── Email ────────────────────────────────────────────────
RESEND_API_KEY=re-your-resend-key
SENDGRID_API_KEY=SG-your-sendgrid-key

# ─── Payments (Stripe) ────────────────────────────────────
STRIPE_API_KEY=sk_live-your-stripe-key
STRIPE_WEBHOOK_SECRET={stripe_secret}

# ─── Supabase ─────────────────────────────────────────────
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_KEY=your-supabase-key

# ─── AWS ──────────────────────────────────────────────────
AWS_ACCESS_KEY_ID=your-aws-access-key
AWS_SECRET_ACCESS_KEY=your-aws-secret-key
AWS_REGION=us-east-1
AWS_S3_BUCKET=autobiz-engine-storage

# ─── Monitoring ───────────────────────────────────────────
SENTRY_DSN=
DISCORD_WEBHOOK_URL=

# ─── Features ─────────────────────────────────────────────
ENABLE_AUTO_APPROVE=false
MAX_BUDGET_PER_BUSINESS=5000.0

# ─── Auth ──────────────────────────────────────────────────
JWT_SECRET={jwt_secret}
ENCRYPTION_KEY={encryption_key}
""".format(
        timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        secret_key=generate_secret(64),
        stripe_secret=generate_secret(32),
        jwt_secret=generate_secret(64),
        encryption_key=generate_secret(32),
    )

    return template


def main():
    parser = argparse.ArgumentParser(description="Rotate AutoBiz Engine secrets")
    parser.add_argument(
        "--env-file",
        default=".env",
        help="Path to the .env file (default: .env)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would change without modifying",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Write new secrets to a different file",
    )
    parser.add_argument(
        "--generate-template",
        action="store_true",
        help="Generate a .env.example template and exit",
    )

    args = parser.parse_args()

    if args.generate_template:
        print(generate_env_template())
        return

    rotate_secrets(args.env_file, dry_run=args.dry_run, output_file=args.output)


if __name__ == "__main__":
    main()